//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicLibrary.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was created.
        /// </summary>
        internal static string CreatedMsg {
            get {
                return ResourceManager.GetString("CreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albn {singer} - get alboms names collection selected by singer name.
        /// </summary>
        internal static string HelpAlbomsBySingerCmdMsg {
            get {
                return ResourceManager.GetString("HelpAlbomsBySingerCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alb {year}- get alboms filtered by year.
        /// </summary>
        internal static string HelpAlbomsByYearCmdMsg {
            get {
                return ResourceManager.GetString("HelpAlbomsByYearCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gr - get alboms names groupped by singer.
        /// </summary>
        internal static string HelpAlbomsGrouppedCmdMsg {
            get {
                return ResourceManager.GetString("HelpAlbomsGrouppedCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create {name} - create new library or rewrite it and set it as current library.
        /// </summary>
        internal static string HelpCreateCmdMsg {
            get {
                return ResourceManager.GetString("HelpCreateCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q - exit.
        /// </summary>
        internal static string HelpExitCmdMsg {
            get {
                return ResourceManager.GetString("HelpExitCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -help - display all available commands.
        /// </summary>
        internal static string HelpHelpCmdMsg {
            get {
                return ResourceManager.GetString("HelpHelpCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb {name} - try to set library as current and create if not exist.
        /// </summary>
        internal static string HelpSetCmdMsg {
            get {
                return ResourceManager.GetString("HelpSetCmdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is needed to set working library.
        /// </summary>
        internal static string NoLibraryMsg {
            get {
                return ResourceManager.GetString("NoLibraryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found.
        /// </summary>
        internal static string NotFoundMsg {
            get {
                return ResourceManager.GetString("NotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was set.
        /// </summary>
        internal static string SetMsg {
            get {
                return ResourceManager.GetString("SetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to testing program for Music Library classes. Please use -help command to see the list of available commands.
        /// </summary>
        internal static string StartMsg {
            get {
                return ResourceManager.GetString("StartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong command.
        /// </summary>
        internal static string WrongCommandMsg {
            get {
                return ResourceManager.GetString("WrongCommandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong &quot;singer name&quot; was entered.
        /// </summary>
        internal static string WrongSingerNameMsg {
            get {
                return ResourceManager.GetString("WrongSingerNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong &quot;year&quot; was entered.
        /// </summary>
        internal static string WrongYearMsg {
            get {
                return ResourceManager.GetString("WrongYearMsg", resourceCulture);
            }
        }
    }
}
